### ISSUE TITLE
Use https://www.npmjs.com/package/naughty-words

### ISSUE THREAD

**Issue by RichardLitt** [words/cuss#13]
Perhaps we should be using https://www.npmjs.com/package/naughty-words?

**Comment by wooorm** [comment]
@RichardLitt Been a while, any reason for that list over `words/profanities`? That list is shorter, and doesn’t have ratings yet?
It’s nice as inspiration for new languages though! (see https://github.com/words/cuss/pull/17 and https://github.com/words/cuss/pull/16)

**Comment by wooorm** [comment]
I think we’re doing great with some of the translations coming in! But let me know if you think this issue is still an issue!

**Comment by RichardLitt** [comment]
Hey, sorry! I haven't had the time to look into it. No problem closing this. :)
