### ISSUE TITLE
Should we write a line explaining how to use cuss in another languages?

### ISSUE THREAD

**Issue by OtacilioN** [words/cuss#22]
I am a beginner in JavaScript and I had some difficulties now about how to use the API in another language, in my case, import the cuss in pt-br. 

Until I figure out that I needed to import using: 

> var cuss = require("cuss/pt-br");

So should we add in the README.md some explanation about how to use the API in languages different than English?

**Comment by wooorm** [comment]
@OtacilioN Yes please! Great idea!! 👍

**Comment by OtacilioN** [comment]
Can I open a pull request adding this? :heart:

**Comment by wooorm** [comment]
Of course! Please do!

**Comment by OtacilioN** [comment]
Today is the elections day in my county, so I will fight for our democracy right now, as soon I go back home I will write this brief tutorial, thanks.

**Comment by wooorm** [comment]
@OtacilioN Take your time!

Relates to: https://github.com/fre5h/DoctrineEnumBundle/pull/12#issuecomment-33023169
