### ISSUE TITLE
Cummings is a street in my area

### ISSUE THREAD

**Issue by RichardLitt** [words/cuss#26]
Cummings, which gets a 2 here and shows up as an error in Alex, is the name of a street in my area and a fairly uncommon, but known, last name. Can we make that word a 1, or in some other fashion make the plural OK, but the singular a 2?

**Comment by wooorm** [comment]
Hah, good idea! Maybe a `0` even? We could add the plural to `profanities` and here in `cuss`. For alex, maybe that works. Or add it in [`ignorePluralize` of `retext-profanities`?](https://github.com/retextjs/retext-profanities/blob/8a337b59dec3578bc3254a4e096588b365d55341/en.js#L10)

**Comment by RichardLitt** [comment]
The plural should be a 1 - it could be a plural gerund (which would be odd, but I can imagine such a use case). The singular should probably remain a 0. I'm not sure which of those two options is best; whatever you think?

**Comment by wooorm** [comment]
Plural 1, singular 2 I presume you meant?
The process is to first add it to profanities, then when it’s released to cuss, and when that’s out we can see if retest-profanities needs an update, not sure!

**Comment by RichardLitt** [comment]
Ah, yeah. Messed up the protocol.

**Comment by RichardLitt** [comment]
I should have checked [cumming](https://en.wikipedia.org/wiki/Cumming), too. Apparently, it is also a common last name and place name. Should we downgrade it to 1?

**Comment by wooorm** [comment]
@RichardLitt Hmm, I still it’s *likely* that the singular is used as a profanity, so I’d say keep it at `2`.
