### ISSUE TITLE
List of other curse word repos

### ISSUE THREAD

**Issue by BrandonKMLee** [words/cuss#40]
For reference:

- https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words
- https://github.com/RobertJGabriel/Google-profanity-words
- https://github.com/MauriceButler/badwords
- https://github.com/words/cuss#support (this repo)
- https://github.com/thisandagain/washyourmouthoutwithsoap
- https://github.com/chucknorris-io/swear-words
- https://github.com/retextjs/retext-profanities#related

**Comment by wooorm** [comment]
hello @BrandonKMLee. Is there anything actionable you wanted us to do here?

**Comment by BrandonKMLee** [comment]
@wooorm it should act mainly as a call for documentation.
But, if it can be done, the curse word tables from each of these tables can be aggregated and de-leet-ified.
For use by things like TextLint https://github.com/textlint/textlint/discussions/753

**Comment by wooorm** [comment]
For the first part, folks can search on GH to also find that, though?
For the last part, that sounds like something you can do yourself?

**Comment by wooorm** [comment]
Closing this. I do welcome more collaboration tho!
